services:
  ros2:
    build: .
    volumes:
      - ../safmc-groundcontrol2:/workspace/safmc-groundcontrol2
      - ../espkinesis_msgs:/workspace/ros2_ws/src/espkinesis_msgs
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    network_mode: host
    privileged: true
    tty: true
    stdin_open: true
    command: bash